Name: Workflow_bf64
SchemaVersion: "1.0"

# Optional - Set automatic triggers.
Triggers:
  - Type: PUSH
    Branches:
      - main
Actions:
    Build:
        Identifier: aws/build@v1
        Inputs:
            Sources:
                - WorkflowSource
        Configuration:     
            Steps:
                - Run: echo "hello"
